apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chaf
      app.kubernetes.io/instance: echo-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chaf
        app.kubernetes.io/instance: echo-server
    spec:
      imagePullSecrets:
        - name: <dockerconfigjson-secret-name>
      containers:
      - image: <docker-private-registry-address>/chaf/echo-server:latest
        name: echo-server
        ports:
        - containerPort: 8088
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
